# .github/workflows/git-sync.yml
on:
  push:
    branches:
      - master
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://${{ secrets.HOSTING }}@github.com//RespctLabs/DAOLandingPage.git"
          source_branch: "main"
          destination_repo: "https://${{ secrets.HOSTING }}@github.com/canvasArtist/DAOLandingPage.git"
          destination_branch: "master"
